### ISSUE TITLE
lalext ice修改为lite ice

### ISSUE THREAD

**Issue by ShimmerGuest** [q191201771/lalext#2]
因为lalext的场景都是作为服务端，必然会有公网ip。在这种情况下我们可以用[lite ice](https://datatracker.ietf.org/doc/html/rfc5245#page-16)。
可以优化：
1. 不用访问stun服务的去获取公网服务器的ip。减少对stun服务的依赖。
2. 减少candidate获取时间，将获取candidate的时间减少为0，大大降低协商时间。

**Comment by ShimmerGuest** [comment]
需要做的事：
a. 在用户启动程序的时候加上一个host ip。如果没有输入，获取网卡的ip。

**Comment by q191201771** [comment]
感谢提交PR，已经merge。
